version: '3'
services:

  web:
    image: local/rhubi9:php8
    build: .
    ports: ['8080:80']
    working_dir: '/app'
    volumes: ['.:/app:z']

  mariadb:
    image: 'mariadb:10.5'
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: 'bug-stats'
      MARIADB_USER: 'bug-stats'
      MARIADB_PASSWORD: 'bugStats'
    volumes: ['bugDB:/var/lib/mysql']

volumes:
  bugDB:
    driver: local
